import { ArticleData } from "../types";
import { SIDNEY_AUTHOR, AUDIT_PUBLISHER } from "../registry";

export const aiMeasurementArticle: ArticleData = {
  id: "AUDITSEO-ARTICLE-AISEARCH-010",
  slug: "/guias/medir-visibilidade-ai-search",
  title: "Como medir visibilidade em AI Search",
  subtitle: "Como transformar menções, representação, fontes, citations, atributos e estabilidade em dados comparáveis sem inventar um score universal de visibilidade em IA. Fechamento metodológico do mini-cluster AI Search.",
  description: "Guia canônico da AUDITSEO sobre como medir visibilidade em AI Search, separando observation, measurement, metric, KPI e score com rigor metodológico.",
  status: "PUBLISHED",
  type: "SUPPORTING",
  cluster: "AI_SEARCH",
  secondaryClusters: ["SEARCH_INTELLIGENCE", "ENTITY_AUTHORITY", "SEO"],
  author: SIDNEY_AUTHOR,
  publisher: AUDIT_PUBLISHER,
  datePublished: "2026-08-14",
  dateModified: "2026-08-14",
  readingTime: "18 min",
  featuredImage: {
    src: "/images/guides/medir-visibilidade-ai-search/featured.webp",
    alt: "Representação visual de matriz multidimensional de observação e mensuração em AI Search.",
    width: 1200,
    height: 630,
  },
  parent: { title: "AI Search", href: "/guias/ai-search" },
  previous: { title: "Citações e Atribuição em Respostas de IA", href: "/guias/citacoes-e-fontes-em-ai-search" },
  related: [
    { title: "AI Search", href: "/guias/ai-search", tag: "Guia" },
    { title: "AI Overviews", href: "/guias/ai-overviews", tag: "Guia" },
    { title: "Citações e Atribuição", href: "/guias/citacoes-e-fontes-em-ai-search", tag: "Guia" },
    { title: "Search Intelligence", href: "/guias/search-intelligence", tag: "Guia" },
  ],
  evidence: ["AUDITSEO-OBS-001", "AUDITSEO-OBS-002"],
  commercialRelation: { title: "Diagnóstico de Autoridade e AI Search", href: "/diagnostico" },
  topicGraph: {
    id: "AUDITSEO-ARTICLE-AISEARCH-010",
    type: "SUPPORTING",
    cluster: "AI_SEARCH",
    secondaryClusters: ["SEARCH_INTELLIGENCE", "ENTITY_AUTHORITY", "SEO"],
    primaryEntity: "AI Search Measurement",
    relatedEntities: ["AI Visibility", "Entity Presence", "Representation Accuracy", "Sidney Santos"],
    parent: "/guias/ai-search",
    previous: "/guias/citacoes-e-fontes-em-ai-search",
    evidenceLinks: ["AUDITSEO-OBS-001", "AUDITSEO-OBS-002"],
    commercialRelation: "/diagnostico",
    status: "PUBLISHED",
  },
  sections: [
    {
      id: "introducao",
      title: "1. Introdução: por que visibilidade em IA não é uma única posição",
      level: 2,
      content: `<p>Em uma SERP tradicional, a mensuração de visibilidade possui parâmetros estabelecidos: posição média, impressões, cliques e taxa de cliques (CTR) fornecidos por relatórios consolidados. Uma URL na terceira posição possui um significado operacional direto, permitindo ao gestor calcular participação e retorno.</p><p>Em ecossistemas de <strong>AI Search</strong>, o objeto observado é substancialmente mais complexo. Uma marca ou organização não ocupa apenas uma "posição"; ela pode ser mencionada no texto, ser descrita corretamente ou incorretamente, ter seu domínio oficial citado como fonte, ser representada por terceiros, aparecer apenas em consultas específicas ou simplesmente ficar ausente. Reduzir essa multiplicidade de estados a um único número arbitrário de 0 a 100 — como tentam fazer diversos scores comerciais de mercado — elimina justamente a granularidade necessária para a tomada de decisão.</p><blockquote class=\"border-l-4 border-amber-500 pl-4 my-4 italic text-neutral-300\"><strong>Visibilidade em AI Search não é uma única posição. É um conjunto de estados observáveis sobre presença, representação, associação, fontes, citations e estabilidade.</strong></blockquote><p>Neste guia de fechamento do nosso mini-cluster, estruturamos a metodologia da AUDITSEO para transformar respostas generativas em dados comparáveis sem recorrer a métricas especulativas.</p>`,
    },
    {
      id: "observation-vs-measurement",
      title: "2. Observation vs. Measurement vs. Metric vs. KPI vs. Score",
      level: 2,
      content: `<p>Para evitar confusões conceituais, a AUDITSEO estabelece uma distinção estrita entre termos frequentemente tratados como sinônimos:</p><ul class=\"space-y-3 my-4\"><li><strong>Observation (Observação):</strong> O registro pontual de um evento na interface (ex: a entidade X apareceu na resposta da query Y na data Z).</li><li><strong>Measurement (Mensuração):</strong> O processo estruturado de capturar e codificar observações segundo critérios padronizados (ex: classificar se a atribuição foi direta ou parcial).</li><li><strong>Metric (Métrica):</strong> A quantificação descritiva de um atributo observado (ex: percentual de queries em que a entidade foi mencionada no conjunto avaliado).</li><li><strong>KPI (Key Performance Indicator):</strong> A métrica selecionada para orientar uma decisão estratégica de negócio ou governança digital.</li><li><strong>Score (Score Composto):</strong> Um índice sintético ponderado (como um índice de 0 a 100) que tenta resumir visibilidade, autoridade e confiança em um único número.</li></ul><p>A AUDITSEO adota métricas descritivas e dimensionais; <strong>rejeitamos scores compostos arbitrários</strong> que não possam ser auditados em sua formulação matemática e em seus dados de origem.</p>`,
    },
    {
      id: "ai-search-measurement-model",
      title: "3. AUDITSEO AI Search Measurement Model",
      level: 2,
      content: `<p>O modelo de mensuração da AUDITSEO opera cruzando coordenadas de contexto com dimensões observáveis:</p><pre class=\"bg-neutral-950 border border-neutral-800 rounded-lg p-4 my-6 overflow-x-auto\">QUERY SET × SYSTEM × SURFACE × DATE × ENTITY\n↓\nPRESENCE | REPRESENTATION | ACCURACY | ASSOCIATION | SOURCE | CITATION | ATTRIBUTION | CONTEXT | STABILITY</pre><p>Cada dimensão é avaliada de forma independente, permitindo identificar, por exemplo, que uma marca possui alta presença nominal, mas baixa acurácia de atributos, ou que suas fontes oficiais aparecem apenas em um subconjunto de superfícies.</p>`,
    },
    {
      id: "core-dimensions",
      title: "4. As Dimensões Fundamentais da Mensuração",
      level: 2,
      content: `<p>A mensuração estruturada decompõe-se em eixos específicos:</p><ul class=\"space-y-3 my-4\"><li><strong>Entity Presence (Presença):</strong> A frequência com que a entidade ou organização é mencionada no conjunto de consultas avaliado.</li><li><strong>Representation Accuracy (Acurácia de Representação):</strong> O grau de correção com que atributos críticos (como fundação, liderança e escopo) são descritos.</li><li><strong>Source & Citation Presence (Presença de Fontes e Citações):</strong> A proporção de respostas em que domínios oficiais ou externos vinculados à marca aparecem como suporte.</li><li><strong>Answer-Source Alignment (Alinhamento):</strong> A verificação qualitativa de que as fontes exibidas realmente sustentam as afirmações da resposta.</li><li><strong>Temporal Stability (Estabilidade):</strong> A consistência da representação ao repetir as capturas em diferentes momentos ou variações de query.</li></ul><p>Essas dimensões formam o painel de controle analítico para agências e marcas.</p>`,
    },
    {
      id: "query-set-methodology",
      title: "5. Metodologia de Query Set e Coleta Controlada",
      level: 2,
      content: `<p>Mensurar visibilidade em IA sem um conjunto estruturado de consultas é apenas navegação aleatória. O protocolo exige:</p><ol class=\"space-y-3 list-decimal list-inside my-4\"><li><strong>Definição do Query Set:</strong> Seleção de perguntas informacionais, comerciais, comparativas e de marca representativas da jornada do usuário.</li><li><strong>Padronização de Contexto:</strong> Fixação de sistema, surface, locale e data de captura para evitar distorções por personalização não controlada.</li><li><strong>Captura Seriada:</strong> Registro integral da resposta, texto gerado, fontes visíveis e links de apoio.</li><li><strong>Codificação Cautelosa:</strong> Aplicação dos modelos de alinhamento e precisão sem inferir motivações internas da plataforma.</li></ol><p>Esse procedimento garante repetibilidade e auditabilidade metodológica.</p>`,
    },
    {
      id: "search-intelligence-and-governance",
      title: "6. Search Intelligence e Evidence Governance no Fechamento",
      level: 2,
      content: `<p>Este artigo conclui a primeira etapa do ecossistema de AI Search da AUDITSEO. Integramos com sucesso a investigação de <a href=\"/guias/ai-overviews\">AI Overviews (#007)</a>, a análise de <a href=\"/guias/recuperacao-de-informacao-ai-search\">Information Retrieval e RAG (#008)</a>, a disciplina de <a href=\"/guias/citacoes-e-fontes-em-ai-search\">Citações e Atribuição (#009)</a> e, agora, a metodologia de <a href=\"/guias/medir-visibilidade-ai-search\">Mensuração (#010)</a>.</p><p>Manter o rigor de evidências — separando documentado, observado, testado, inferido e recomendado — é o que diferencia a análise profissional de especulações de mercado. Para agências que desejam auditar sua presença em ecossistemas generativos, conheça nossa solução de <a href=\"/diagnostico\">Diagnóstico de Autoridade</a> ou explore o <a href=\"/estudos-busca-ia\">Search Intelligence Lab</a>.</p>`,
    },
    {
      id: "measurement-objects",
      title: "7. O que herdamos de #007, #008 e #009",
      level: 2,
      content: `<p>O #010 não começa do zero. Ele recebe três camadas de objetos já definidos. Do #007, herdamos a separação entre evento de interface e mecanismo interno: uma AI Overview ou resposta sintética é uma superfície observável, não uma janela transparente para o pipeline. Do #008, herdamos a distinção entre retrieval, generation, grounding, source access e retrieval trace. Do #009, herdamos a tipologia Source, Citation, Mention e Attribution, além do Answer-Source Alignment Model.</p><p>A nova propriedade do #010 é integrar esses objetos em uma unidade de mensuração que permita comparação com denominador explícito. A pergunta deixa de ser apenas “o que apareceu?” e passa a ser “em qual universo de observações isso apareceu, com qual regra de inclusão, em que período e com que implicação para a decisão?”. Essa integração é a ponte metodológica entre Search Intelligence e governança de negócio.</p><p>O artigo usa Observations #001 e #002 apenas em seus contextos reais. A #001 ilustra associação temática e desambiguação; a #002 ilustra presença de entidade com atributo incorreto. Nenhuma delas é tratada como experimento novo ou como validação de causalidade.</p>`,
    },
    {
      id: "unit-of-observation",
      title: "8. A unidade de observação: uma query em um contexto definido",
      level: 2,
      content: `<p>Uma observação precisa ter uma unidade identificável. A unidade editorial proposta é:</p><pre class=\"bg-neutral-950 border border-neutral-800 rounded-lg p-4 my-6 overflow-x-auto\">OBSERVATION UNIT = ONE QUERY × ONE SYSTEM × ONE SURFACE × ONE TIMESTAMP / CONTEXT</pre><p>Isso significa que uma resposta observada no Google AI Overview não deve ser misturada automaticamente com uma resposta do ChatGPT Search, nem uma captura de hoje com uma captura de três meses atrás. Cada combinação de query, sistema, surface, timestamp, locale e estado de sessão representa um contexto que pode produzir uma resposta diferente.</p><p>Quando a análise exige mais precisão, o registro deve incluir hora, idioma, país, localização relevante, dispositivo, sessão autenticada ou anônima e se houve histórico prévio. Não é necessário presumir que todo fator é causal; basta conservar os campos para que a interpretação não seja artificialmente mais forte do que a captura permite.</p>`,
    },
    {
      id: "observation-record",
      title: "9. Observation Record: o contrato mínimo de captura",
      level: 2,
      content: `<p>O registro de uma observação deve ser compreensível por outra pessoa que não participou da captura. O contrato mínimo contém:</p><table class=\"w-full text-sm my-6 border-collapse\"><thead><tr><th class=\"text-left border-b border-neutral-700 p-2\">Campo</th><th class=\"text-left border-b border-neutral-700 p-2\">Função</th></tr></thead><tbody><tr><td class=\"border-b border-neutral-800 p-2\">Query e query class</td><td class=\"border-b border-neutral-800 p-2\">Define a intenção e o universo temático.</td></tr><tr><td class=\"border-b border-neutral-800 p-2\">System e surface</td><td class=\"border-b border-neutral-800 p-2\">Preserva a interface e o comportamento específico.</td></tr><tr><td class=\"border-b border-neutral-800 p-2\">Date, time e locale</td><td class=\"border-b border-neutral-800 p-2\">Delimita o período e a localização da observação.</td></tr><tr><td class=\"border-b border-neutral-800 p-2\">Entity e organization</td><td class=\"border-b border-neutral-800 p-2\">Indica o objeto da análise e possíveis relações.</td></tr><tr><td class=\"border-b border-neutral-800 p-2\">Answer, entity e attribute states</td><td class=\"border-b border-neutral-800 p-2\">Codifica presença, correção e representação.</td></tr><tr><td class=\"border-b border-neutral-800 p-2\">Sources, citations e attribution</td><td class=\"border-b border-neutral-800 p-2\">Reaproveita os objetos de #009 sem colapsá-los.</td></tr><tr><td class=\"p-2\">Notes e limitations</td><td class=\"p-2\">Registra ambiguidade, indisponibilidade ou alteração da interface.</td></tr></tbody></table><p>Screenshot e raw evidence devem ser preservados quando autorizados. A captura prova o estado observável; não prova todo o backend. A ausência de um campo deve ser codificada como <strong>UNKNOWN</strong> ou <strong>NOT AVAILABLE</strong>, e não como “não aconteceu”.</p>`,
    },
    {
      id: "observation-vs-measurement",
      title: "10. Uma observação isolada não é uma medição robusta",
      level: 2,
      content: `<p>Uma observação é uma captura de estado. Measurement exige protocolo, população definida, regras de inclusão, repetibilidade e comparação. Se uma entidade aparece em uma resposta, temos evidência de presença nessa query, naquele sistema e naquele momento. Ainda não temos Entity Presence Rate, estabilidade ou comparação entre sistemas.</p><blockquote class=\"border-l-4 border-amber-500 pl-4 my-4 italic text-neutral-300\">Uma resposta isolada pode gerar evidência. Não gera, sozinha, uma métrica robusta.</blockquote><p>Uma medição pode ser construída com 20 queries em uma surface específica e quatro datas, desde que o denominador e os critérios sejam mantidos. O número 20 não é um mínimo universal. Ele é apenas um exemplo de protocolo. A amostra deve ser suficiente para o objetivo, a diversidade de queries, a disponibilidade do sistema, os recursos e o nível de inferência pretendido.</p>`,
    },
    {
      id: "dimension-presence-correctness",
      title: "11. Dimensões 1 a 3: presença, entidade correta e acurácia de atributos",
      level: 2,
      content: `<p>A primeira pergunta é simples: a entidade apareceu? Os estados possíveis são <strong>YES</strong>, <strong>NO</strong> e <strong>UNCLEAR</strong>. Essa presença pode depois alimentar uma métrica descritiva chamada Entity Presence Rate, mas não é um authority score e não diz se a representação foi positiva.</p><p>A segunda pergunta é: a entidade correta apareceu? Aqui conectamos a mensuração à desambiguação. Os estados são <strong>CORRECT</strong>, <strong>INCORRECT</strong> e <strong>UNCLEAR</strong>. A <a href=\"/estudos-busca-ia/reconhecimento-de-entidade-por-contexto\">Observation #001</a> é um exemplo de como a alteração de contexto pode mudar a identificação observável, sem autorizar uma regra causal universal.</p><p>A terceira dimensão avalia atributos: fundador, ano, localização, serviço, função, categoria ou outro atributo definido no protocolo. Os estados são <strong>CORRECT</strong>, <strong>PARTIAL</strong>, <strong>INCORRECT</strong> e <strong>NOT OBSERVABLE</strong>. A <a href=\"/estudos-busca-ia/entidade-correta-atributo-incorreto-ai-search\">Observation #002</a> é um caso útil porque a entidade foi encontrada, mas um atributo temporal foi representado incorretamente. Presença alta com acurácia baixa é risco de representação, não sucesso.</p>`,
    },
    {
      id: "dimension-association-quality",
      title: "12. Dimensões 4 a 6: organização, tópico e fontes",
      level: 2,
      content: `<p><strong>Organization Association</strong> pergunta se pessoa, marca e organização foram relacionadas corretamente. A relação entre uma pessoa e sua organização não deve ser presumida porque os nomes aparecem próximos. O registro exige evidência textual e, quando necessário, uma source que sustente a relação.</p><p><strong>Topic Association</strong> verifica se a entidade aparece conectada ao tema desejado. Uma marca pode aparecer em queries de SEO, mas não nas de Entity Authority; uma pessoa pode aparecer como autor, mas não como especialista no tema solicitado. Essa cobertura depende do query cluster e deve ser analisada no universo adequado.</p><p><strong>Source Presence</strong> registra se o domínio oficial, uma fonte de terceiro, ambos ou nenhum aparecem. A presença de uma fonte oficial é apenas uma dimensão observável. Ela não conclui autoridade, endorsement, preferência algorítmica ou qualidade universal. O #009 já demonstrou por que source presence, citation presence e attribution devem permanecer separados.</p>`,
    },
    {
      id: "dimension-citation-attribution",
      title: "13. Dimensões 7 a 11: citation, attribution, contexto e alinhamento",
      level: 2,
      content: `<p><strong>Citation Presence</strong> registra YES, NO ou NOT AVAILABLE. “Não há citation visível” é diferente de “a interface não oferece citation” e de “a captura não permitiu verificar”. <strong>Attribution</strong> pergunta se uma claim foi associada a uma source ou entidade observável: YES, NO ou UNCLEAR.</p><p>O <strong>Recommendation Context</strong> separa recommended, compared, mentioned neutrally, criticized, excluded e unclear. Menção não é recomendação. Não criamos sentiment score complexo nesta fase; apenas preservamos o contexto que altera a interpretação de presença.</p><p><strong>Representation Quality</strong> também não é um score único. É um framework diagnóstico composto por identity, relation, attribute, topic e context. Já <strong>Source Alignment</strong> reaproveita o Answer-Source Alignment de #009: DIRECT, PARTIAL, WEAK, UNCLEAR, CONFLICTING e NOT ASSESSABLE. Cada componente responde uma pergunta diferente e pode revelar um diagnóstico que um índice único esconderia.</p>`,
    },
    {
      id: "dimension-stability-volatility",
      title: "14. Dimensões 12 e 13: estabilidade e volatilidade",
      level: 2,
      content: `<p>Uma representação é estável quando mantém, em observações comparáveis, estados semelhantes de entity presence, atributos, fontes, citations e recomendação. Sem repetição, <strong>STABILITY = UNKNOWN</strong>. Uma captura única não pode produzir uma conclusão temporal.</p><p><strong>Volatility</strong> descreve alterações entre observações comparáveis. Pode ocorrer no texto da resposta, source, citation, entidade, atributo ou recommendation context. Volatilidade é uma mudança observada; não é diagnóstico de causa. A mudança pode refletir atualização do sistema, mudança de conteúdo, query rewriting, locale, disponibilidade da surface, estado de sessão ou muitos fatores não isolados.</p><p>A comparação temporal usa T0, T1, T2 e T3 como pontos de observação. Podemos relatar que a presença aumentou, que o atributo mudou ou que a fonte desapareceu. Não podemos dizer automaticamente que uma intervenção no site causou o efeito sem controles, repeatability, confounder review ou desenho experimental apropriado.</p>`,
    },
    {
      id: "query-set-design",
      title: "15. Query Set: o universo da mensuração",
      level: 2,
      content: `<p>Measurement começa pela pergunta: <strong>quais queries estamos medindo?</strong> Um query set define o universo de observação e torna qualquer percentual interpretável. As classes editoriais podem incluir brand, person, product, service, category, informational, comparative, commercial, relational e recommendation.</p><p>Essa taxonomia é um modelo da AUDITSEO, não uma classificação universal das plataformas. Um conjunto pode ser estático, mantendo as mesmas queries ao longo do tempo para comparação longitudinal, ou dinâmico, evoluindo para descoberta de novas formulações. O conjunto dinâmico é útil para exploração, mas não deve ser comparado diretamente com uma série estática sem explicar a mudança de universo.</p><p>Também não devemos inventar pesos. Dez queries de marca e cinquenta queries genéricas não podem ser agregadas como se representassem a mesma distribuição sem uma regra de weighting explicitamente definida. O weighting precisa ser justificável pela decisão de negócio, não escolhido para favorecer um resultado.</p>`,
    },
    {
      id: "system-surface-time-locale",
      title: "16. Sistema, surface, período, locale e sessão",
      level: 2,
      content: `<p>Google AI Overviews, Google AI Mode, ChatGPT Search, Perplexity, Gemini e Copilot não devem ser misturados automaticamente em um denominador único. Cada sistema possui interface, disponibilidade, comportamento de fontes e tratamento de query próprios. Mesmo dentro de uma empresa, duas surfaces podem operar de modo diferente.</p><p>O período precisa ser preservado porque outputs de IA são temporais. Registrar data é obrigatório; hora pode ser necessária em sistemas com atualização rápida. Locale inclui idioma, país e localização quando relevante. Não é seguro presumir que uma resposta global seja idêntica à resposta em português brasileiro.</p><p>O estado de sessão deve ser registrado quando observável: login, sessão nova, personalização, histórico ou contexto de conversa. Não devemos alegar isolamento perfeito quando a plataforma não permite controlar todos esses fatores. A honestidade do protocolo está em conservar a limitação, não em escondê-la.</p>`,
    },
    {
      id: "sample-denominator",
      title: "17. Amostra, denominador e estado elegível",
      level: 2,
      content: `<p>Qual é a nossa amostra? Dez queries, cem ou mil? Não existe tamanho mínimo universal. O número depende do objetivo, da diversidade do query set, da disponibilidade do sistema, dos recursos e do grau de inferência desejado.</p><p>O denominador é talvez a parte mais importante da medição. Toda porcentagem precisa responder: <strong>percentual de quê?</strong> “A marca teve 60% de AI Visibility” não significa nada sem declarar se o denominador são todas as queries, as queries elegíveis, apenas respostas generativas ou apenas observações em que a entidade foi mencionada.</p><p>Um <strong>eligible observation</strong> é uma observação que satisfaz as condições da métrica. Para AI Overview Presence Rate, a ausência da AI Overview pode entrar no denominador, porque a pergunta é sobre presença da surface. Para Citation Rate conditional on AIO Presence, o denominador deve incluir apenas observações em que a AI Overview existe. Zero citations exibidas é diferente de citations não disponíveis na interface; missingness nunca deve ser convertido automaticamente em zero.</p>`,
    },
    {
      id: "conditional-metrics",
      title: "18. Métricas condicionais: medir sem esconder o universo",
      level: 2,
      content: `<p>Métricas condicionais tornam o contrato mais honesto. Um exemplo é <strong>Official Source Citation Rate given Entity Mention</strong>: o numerador conta observações em que a fonte oficial foi citada, enquanto o denominador inclui apenas observações em que a entidade apareceu. Essa métrica responde uma pergunta diferente de Official Source Presence Rate sobre todas as observações elegíveis.</p><pre class=\"bg-neutral-950 border border-neutral-800 rounded-lg p-4 my-6 overflow-x-auto\">ENTITY PRESENCE RATE = entity-present observations / eligible observations\nCORRECT REPRESENTATION RATE = correct entity + required attributes / entity-present observations\nOFFICIAL SOURCE PRESENCE RATE = official source visible / eligible observations\nCITATION RATE CONDITIONAL = citations present / generative responses where condition holds</pre><p>As fórmulas são exemplos metodológicos, não padrões universais. O mesmo numerador pode produzir interpretações completamente diferentes quando o denominador muda. O contrato da métrica deve declarar query set, sistema, surface, período, inclusão, exclusão, missing state e limitações.</p>`,
    },
    {
      id: "metric-cards",
      title: "19. Metric Card: como documentar uma métrica",
      level: 2,
      content: `<p>Uma métrica só é auditável quando possui uma ficha completa:</p><table class=\"w-full text-sm my-6 border-collapse\"><thead><tr><th class=\"text-left border-b border-neutral-700 p-2\">Campo</th><th class=\"text-left border-b border-neutral-700 p-2\">Exemplo: Entity Presence Rate</th></tr></thead><tbody><tr><td class=\"border-b border-neutral-800 p-2\">Metric name</td><td class=\"border-b border-neutral-800 p-2\">Entity Presence Rate</td></tr><tr><td class=\"border-b border-neutral-800 p-2\">Question</td><td class=\"border-b border-neutral-800 p-2\">Com que frequência a entidade aparece?</td></tr><tr><td class=\"border-b border-neutral-800 p-2\">Unit</td><td class=\"border-b border-neutral-800 p-2\">Query-system-surface-date observation</td></tr><tr><td class=\"border-b border-neutral-800 p-2\">Query set / period</td><td class=\"border-b border-neutral-800 p-2\">Cluster temático definido / período declarado</td></tr><tr><td class=\"border-b border-neutral-800 p-2\">Numerator</td><td class=\"border-b border-neutral-800 p-2\">Observações contendo a entidade correta</td></tr><tr><td class=\"border-b border-neutral-800 p-2\">Denominator</td><td class=\"border-b border-neutral-800 p-2\">Observações elegíveis</td></tr><tr><td class=\"border-b border-neutral-800 p-2\">Exclusions / missingness</td><td class=\"border-b border-neutral-800 p-2\">Query bloqueada, sistema indisponível e entidade unclear classificados separadamente</td></tr><tr><td class=\"p-2\">Limitation</td><td class=\"p-2\">Não mede acurácia, citation, sentiment ou autoridade</td></tr></tbody></table><p>Uma metric card permite que duas pessoas reproduzam a mesma leitura. Sem ela, um número pode parecer preciso e ainda ser semanticamente vazio.</p>`,
    },
    {
      id: "share-of-model",
      title: "20. Share of Model: termo de mercado, não KPI canônico",
      level: 2,
      content: `<p>Share of Model não deve ser descartado nem adotado cegamente. É um termo de mercado cuja utilidade depende do contrato da métrica. Precisamos perguntar: o que “share” significa? Qual é o denominador? O que conta como mention? Quais sistemas, surfaces, queries e períodos estão incluídos? Citation e recommendation contam? A posição importa? Múltiplas marcas podem aparecer na mesma resposta?</p><p>Definições hipotéticas produzem números diferentes:</p><ul class=\"space-y-3 my-4\"><li><strong>Definição A:</strong> menções da marca divididas pelo total de menções de marcas.</li><li><strong>Definição B:</strong> queries em que a marca aparece divididas pelo total de queries.</li><li><strong>Definição C:</strong> recomendações contendo a marca divididas pelo total de queries de recomendação.</li></ul><p>Essas definições não são equivalentes. Portanto, a classificação AUDITSEO é: <strong>Share of Model = MARKET TERM / METHODOLOGY-DEPENDENT</strong>. Pode ser útil se operacionalmente definido, mas não é um KPI universal e não é automaticamente o novo Share of Voice. Qualquer uso exige metric card, query set, denominador e disclaimer de comparabilidade.</p>`,
    },
    {
      id: "zero-to-100",
      title: "21. Por que eu não começaria por um score de 0 a 100",
      level: 2,
      content: `<p>Começar por um score composto parece atraente porque produz uma narrativa simples. O problema é que simplicidade pode ocultar diagnóstico. A primeira dificuldade é <strong>weight arbitrariness</strong>: quanto presença vale em relação a acurácia, source, citation, recommendation e estabilidade? A segunda é <strong>loss of diagnostic detail</strong>: presença alta e atributos errados podem resultar em score médio sem mostrar o risco.</p><p>Há também <strong>false precision</strong>. Um 73 não é necessariamente mais informativo que um 68 quando a fórmula, o denominador e os estados missing não são transparentes. A comparação entre sistemas é ainda mais frágil porque surfaces diferentes não exibem os mesmos elementos. Interfaces mudam, query sets mudam e o significado do score pode mudar sem que o número pareça diferente.</p><blockquote class=\"border-l-4 border-amber-500 pl-4 my-4 italic text-neutral-300\">Uma matriz diagnóstica que mostra presença alta com acurácia baixa é mais útil para decisão do que um score agregado que chama o estado de “bom”.</blockquote><p>Por isso, o #010 não cria AI Visibility Score, GEO Score ou AI Authority Score. A decisão deve partir de dimensões explícitas e dos objetivos do negócio.</p>`,
    },
    {
      id: "representation-matrix",
      title: "22. Matriz de estado de representação",
      level: 2,
      content: `<p>A leitura multidimensional pode ser organizada em uma matriz descritiva, sem pesos e sem chamar os quadrantes de score:</p><table class=\"w-full text-sm my-6 border-collapse\"><thead><tr><th class=\"text-left border-b border-neutral-700 p-2\">Estado observado</th><th class=\"text-left border-b border-neutral-700 p-2\">Interpretação diagnóstica</th></tr></thead><tbody><tr><td class=\"border-b border-neutral-800 p-2\"><strong>Alta presença + alta acurácia</strong></td><td class=\"border-b border-neutral-800 p-2\">Estado forte de representação observada, condicionado ao query set.</td></tr><tr><td class=\"border-b border-neutral-800 p-2\"><strong>Alta presença + baixa acurácia</strong></td><td class=\"border-b border-neutral-800 p-2\">Risco de representação: a entidade aparece, mas atributos ou relações estão errados.</td></tr><tr><td class=\"border-b border-neutral-800 p-2\"><strong>Baixa presença + alta acurácia</strong></td><td class=\"border-b border-neutral-800 p-2\">Presença limitada, porém correta nas ocorrências observadas.</td></tr><tr><td class=\"p-2\"><strong>Baixa presença + baixa acurácia</strong></td><td class=\"p-2\">Estado fraco ou instável, exigindo investigação do query set e das fundações.</td></tr></tbody></table><p>A matriz é uma ferramenta de interpretação. Ela não substitui análise de source, context, topic association ou recommendation. Também não deve ser agregada em um valor único sem um contrato explícito, algo que não faz parte do escopo R12.</p>`,
    },
    {
      id: "time-series-causality",
      title: "23. Time series, baseline e causalidade",
      level: 2,
      content: `<p>Uma série temporal pode comparar T0, T1, T2 e T3 em presença, acurácia, sources e citations. A baseline deve ser definida antes da interpretação: query set, system, surface, locale, período e critérios. Uma baseline retroativa escolhida depois de ver o resultado pode produzir uma narrativa conveniente, mas não uma mensuração confiável.</p><p>Baseline é o estado anterior da própria entidade. Benchmark é uma referência comparativa. Um industry benchmark exige metodologia comparável; datasets de vendors diferentes não devem ser combinados como se possuíssem o mesmo universo. A mudança entre T0 e T1 também não prova impacto de intervenção. Se o site foi alterado entre os pontos, ainda precisamos considerar mudanças de sistema, conteúdo concorrente, disponibilidade de surface, query drift e outros confundidores.</p><p>Para afirmar causalidade, seriam necessários controles, repetição, tratamento de confundidores e desenho experimental apropriado. Nesta fase, relatamos mudança observada, não impacto causal. Essa disciplina mantém a classificação de Evidence Governance dentro do que o dado suporta.</p>`,
    },
    {
      id: "missingness-data-quality",
      title: "24. Missingness, zero e qualidade dos dados",
      level: 2,
      content: `<p>Estados ausentes são parte do modelo, não ruído a ser apagado. Exemplos incluem no generative answer, no citations displayed, system unavailable, query blocked e no entity mention. Cada condição responde uma pergunta diferente.</p><p><strong>Zero ≠ Missing.</strong> Zero citations observed significa que a interface permitiu verificar citations e nenhuma foi exibida. Citations not available significa que a surface não oferece esse elemento ou que não foi possível acessá-lo. <strong>UNKNOWN</strong> deve ser usado quando a classificação não pode ser feita. Forçar YES/NO produz falsa precisão.</p><p>O QA de mensuração deve procurar observações duplicadas, query mismatch, locale errado, data errada, ambiguidade de entidade, perda de screenshot, erro de parsing de source e alterações de interface. A trilha de auditoria deve reter timestamp, query, system, surface, referência de evidência bruta, classificação e notas de revisão. Não construímos database ou monitoring platform agora; descrevemos o contrato para uma futura implementação controlada.</p>`,
    },
    {
      id: "manual-automated",
      title: "25. Mensuração manual, automatizada e risco de classificação",
      level: 2,
      content: `<p>A mensuração manual oferece interpretação contextual elevada, mas escala pouco. O analista consegue avaliar nuance de attribution, recommendation, entity identity e source role, embora esteja sujeito a cansaço e inconsistência. A automação oferece escala, mas exige regras robustas de classificação, acesso à interface ou API e controles contra mudanças de layout.</p><p>Um classificador automatizado pode confundir entidades homônimas, considerar uma mention como recommendation, atribuir uma source à organização errada ou interpretar o tom de uma resposta fora de contexto. O uso de automação não elimina human QA. Ele desloca a necessidade de revisão para amostras, casos ambíguos, mudanças de interface e exceções.</p><p>O workflow recomendado é começar manualmente para definir o contrato, normalizar estados, testar casos-limite e só depois avaliar se alguma etapa pode ser automatizada. Não há, neste R12, comparação de ferramentas ou construção de engine. O foco é a validade da medida, não a promessa de escala.</p>`,
    },
    {
      id: "measurement-pipeline",
      title: "26. AUDITSEO Measurement Pipeline",
      level: 2,
      content: `<p>O modelo editorial de pipeline traduz uma pergunta de negócio em uma medição auditável:</p><pre class=\"bg-neutral-950 border border-neutral-800 rounded-lg p-4 my-6 overflow-x-auto\">BUSINESS QUESTION\n↓\nQUERY SET\n↓\nOBSERVATION CONTRACT\n↓\nDATA CAPTURE\n↓\nENTITY / SOURCE / CITATION CLASSIFICATION\n↓\nMETRIC CONTRACT\n↓\nMEASUREMENT\n↓\nINTERPRETATION\n↓\nACTION\n↓\nRE-MEASUREMENT</pre><p>O workflow de Search Intelligence é equivalente em linguagem operacional: <strong>Define → Capture → Normalize → Classify → Measure → Compare → Interpret → Decide → Re-measure</strong>. A repetição não significa criar um sistema automático; significa preservar um protocolo que possa ser revisado.</p><p>Essa separação também protege o cliente de medir tudo ao mesmo tempo. A pergunta “somos mencionados?” pode exigir Entity Presence Rate. “Somos representados corretamente?” exige Entity Correctness e Attribute Accuracy. “Nosso domínio oficial aparece?” exige Official Source Presence. Cada decisão aponta para uma dimensão diferente.</p>`,
    },
    {
      id: "business-scenarios",
      title: "27. Métrica depende da pergunta de negócio",
      level: 2,
      content: `<p>Uma marca em fase de descoberta pode priorizar Entity Presence Rate e Topic Association Coverage. Uma pessoa especialista pode priorizar Entity Correctness, Attribute Accuracy e Organization Association. Um produto em mercado competitivo pode observar Recommendation Presence, Attribute Accuracy e Source Presence. Uma organização institucional pode priorizar a presença do domínio oficial e a correção de seus atributos.</p><p>O mesmo evento pode ser positivo para um objetivo e insuficiente para outro. A presença do nome em uma resposta não indica recomendação. A recomendação sem source oficial pode exigir uma pergunta de attribution. A source oficial sem menção central à entidade pode ser uma dimensão de fonte, não de presença da marca.</p><p>Um KPI só existe quando uma métrica se relaciona a uma decisão. Se o objetivo é corrigir um ano de fundação, Attribute Error Rate pode ser mais útil que Entity Presence Rate. Se o objetivo é entender descoberta por categoria, Topic Association Coverage pode ser relevante. Não devemos transformar cada métrica disponível em KPI; medir apenas o que informa uma decisão é parte da governança.</p>`,
    },
    {
      id: "entity-authority-bridge",
      title: "28. A ponte com Entity Authority sem prometer causalidade",
      level: 2,
      content: `<p>Entity Authority fornece fundações de identidade, desambiguação, consistência, autoria e corroboração. O #010 pergunta se essas fundações se refletem corretamente nos outputs observados. Não pergunta se elas causam citation ou se uma Entity Home funciona como anchor universal.</p><p>O bridge é operacional: identidade ajuda a especificar qual entity deveria ser reconhecida; desambiguação ajuda a avaliar se a entity correta foi encontrada; consistência ajuda a verificar atributos ao longo do tempo; autoria ajuda a contextualizar a origem de conteúdo; corroboração ajuda a comparar fontes externas. A medição avalia o estado representado, não a arquitetura interna que teria produzido o estado.</p><p>As Observations #001 e #002 permanecem exemplos de dimensões: a primeira relaciona contexto e topic association; a segunda relaciona entity presence e attribute accuracy. Não adicionamos Observation nova e não transformamos o bridge em um modelo causal.</p>`,
    },
    {
      id: "planned-research",
      title: "29. Planned Research Questions e limites do R12",
      level: 2,
      content: `<p>O fechamento do mini-cluster consolida perguntas que permanecem planejadas:</p><ul class=\"space-y-3 my-4\"><li><strong>RQ-MEA-001:</strong> Quanto Entity Presence varia entre observações repetidas de um query set fixo?</li><li><strong>RQ-MEA-002:</strong> Quão estável é Attribute Accuracy entre sistemas e surfaces?</li><li><strong>RQ-MEA-003:</strong> Como Official Source Presence varia por query class?</li><li><strong>RQ-MEA-004:</strong> Quão diferentes são resultados quando Share of Model usa denominadores distintos?</li><li><strong>RQ-MEA-005:</strong> Qual é o efeito de missing states na interpretação de Citation Presence Rate?</li></ul><p>Essas questões não são Observations, Experiments ou Research Items executados. São dependências para investigação futura. **NEW OBSERVATIONS = 0**, **NEW EXPERIMENTS = 0** e **NEW RESEARCH ITEMS = 0**. Não foi criado measurement engine, tracking platform, dashboard, database, AI Visibility Score, GEO Score ou Share of Model automático.</p>`,
    },
    {
      id: "references",
      title: "30. Referências e documentação consultada",
      level: 2,
      content: `<p>A fundação de fontes foi registrada antes da redação em <code>qa/r12-ai-search-measurement-source-foundation.md</code>. A documentação oficial do Google informa como os dados de AI features são tratados no relatório de performance e estabelece limites do que é observável [1] [2]. As Observations #001 e #002 são utilizadas somente em seus contextos reais [3].</p><ol class=\"space-y-3 list-decimal list-inside my-4\"><li><a href=\"https://developers.google.com/search/docs/appearance/ai-features#measuring-the-performance-of-your-site\" target=\"_blank\" rel=\"noreferrer\">Google Search Central — Measuring the performance of your site in AI features</a>.</li><li><a href=\"https://support.google.com/webmasters/answer/7576553\" target=\"_blank\" rel=\"noreferrer\">Google Search Console Help — Performance report</a>.</li><li><a href=\"/estudos-busca-ia\">AUDITSEO — Search Intelligence Lab</a>, com as Observations #001 e #002 classificadas como OBSERVADO.</li><li><a href=\"/guias/citacoes-e-fontes-em-ai-search\">AUDITSEO — Citações e atribuição em respostas de IA</a>.</li><li><a href=\"/guias/recuperacao-de-informacao-ai-search\">AUDITSEO — Recuperação de Informação em AI Search</a>.</li></ol><p>As referências de plataforma foram consultadas em 14 de agosto de 2026. A documentação pode mudar; claims sobre produtos devem ser revalidados quando a surface analisada for alterada.</p>`,
    },
    {
      id: "measurement-contract",
      title: "31. AUDITSEO Measurement Contract, Audit Trail e Screenshot Evidence",
      level: 2,
      content: `<p>Todo indicador precisa declarar um <strong>AUDITSEO Measurement Contract</strong> antes de ser calculado. O contrato contém: nome da métrica, pergunta que ela responde, unidade de observação, query set, system, surface, período, numerador, denominador, regra de inclusão, regra de exclusão, estado missing, limitações e uso de negócio. Sem esses campos, um percentual pode ser matematicamente correto e metodologicamente incomparável.</p><p>O <strong>Audit Trail</strong> conserva timestamp, query original, query class, sistema, surface, locale, sessão quando relevante, referência da evidência bruta, classificação aplicada e notas de revisão. O objetivo não é construir um database de monitoring nesta fase. É garantir que uma conclusão possa voltar à observação que a originou e que uma correção de classificação possa ser rastreada.</p><p><strong>Screenshot Evidence</strong> preserva o estado observável da interface: texto gerado, cards, fontes, citations, ausência de resposta e contexto visual. Uma captura não revela o pipeline completo de backend, não informa o conjunto de documentos descartados e não prova causalidade. Ainda assim, ela evita que a análise dependa apenas da memória do analista. Raw capture, transcrição e classificação devem permanecer associados ao mesmo observation record.</p><p>Na prática, o contrato permite separar três perguntas que muitas vezes são misturadas: o que foi visto, como foi agregado e que decisão pode ser tomada. Essa separação é a condição mínima para que Search Intelligence produza evidência útil sem fabricar precisão.</p>`,
    },
    {
      id: "closing-methodological-gate",
      title: "32. Conclusão: medir para decidir, não para produzir um número",
      level: 2,
      content: `<p>AI Search Visibility não é um ranking escondido esperando ser descoberto. É uma coleção de estados observáveis que precisam ser definidos, capturados, normalizados, comparados e interpretados dentro de um protocolo. Presence, representation, accuracy, association, source, citation, attribution, recommendation e stability respondem perguntas diferentes.</p><p>O trabalho de mensuração profissional começa com uma pergunta de negócio, não com uma ferramenta ou score. Define um query set, declara o denominador, preserva system, surface, data e locale, separa zero de missing, registra unknown, conserva evidência e evita atribuir causalidade a mudanças que ainda não foram testadas. O resultado pode ser menos conveniente que um número de 0 a 100, mas é muito mais útil para decidir o que investigar e o que corrigir.</p><p>Este é o fechamento metodológico do mini-cluster AI Search. #007 ensinou a observar a superfície; #008 ensinou a separar retrieval, grounding e source; #009 ensinou a auditar citation e attribution; #010 transforma esses objetos em um contrato de mensuração multidimensional. O próximo passo responsável é validar perguntas específicas com protocolos específicos — sem criar um KPI universal antes de saber qual decisão ele deve orientar.</p>`,
    },
  ],
  faq: [
    {
      question: "O que é AI Search Visibility segundo a AUDITSEO?",
      answer: "É o conjunto de estados observáveis que descrevem se e como uma entidade, organização ou marca aparece e é representada em superfícies generativas dentro de um protocolo definido."
    },
    {
      question: "Por que a AUDITSEO rejeita scores compostos de visibilidade?",
      answer: "Porque índices sintéticos de 0 a 100 misturam dimensões distintas (presença, acurácia, citations) em uma fórmula opaca que impede a auditoria e a tomada de decisão estratégica."
    },
    {
      question: "Como o Search Console se relaciona com a mensuração de AI Search?",
      answer: "Conforme documentação oficial do Google, o tráfego gerado por AI Overviews e AI features é incorporado ao relatório de performance padrão sob a busca Web, exigindo análise qualitativa complementar."
    }
  ],
};
